In [1]:
import pandas as pd
import numpy as np

In [2]:
pitching_stats = pd.read_csv("Pitching.csv")

In [3]:
pitching_stats = pitching_stats.loc[pitching_stats['yearID'] >= 2000]

In [4]:
pitching_stats.drop(['SF', 'SH', 'GIDP','WP', 'HBP','BFP', 'BAOpp', 'GS', 'CG','SHO', 
                    'IBB', 'BK','GF'], axis = 1)

,playerID,yearID,stint,teamID,lgID,W,L,G,SV,IPouts,H,ER,HR,BB,SO,ERA,R
32904,abbotpa01,2000,1,SEA,AL,9,7,35,0,537,164,84,23,80,100,4.22,89
32905,aceveju01,2000,1,MIL,NL,3,7,62,0,248,77,35,11,31,51,3.81,38
32906,adamste01,2000,1,LAN,NL,6,9,66,2,253,80,33,6,39,56,3.52,42
32907,aguilri01,2000,1,CHN,NL,1,2,54,29,143,47,26,11,18,38,4.91,28
32908,aldresc01,2000,1,PHI,NL,1,3,23,0,61,23,13,3,10,21,5.75,14
32909,alfonan01,2000,1,FLO,NL,5,6,68,45,210,82,33,7,24,47,4.24,35
32910,almanar01,2000,1,FLO,NL,4,2,67,0,139,38,25,3,43,46,4.86,27
32911,almanca01,2000,1,SDN,NL,4,5,62,0,209,73,34,12,25,56,4.39,35
32912,alvarju01,2000,1,ANA,AL,0,0,11,0,18,14,9,3,7,2,13.50,9
32913,anderbr02,2000,1,ARI,NL,11,7,33,0,640,226,96,38,39,104,4.05,101
32914,anderji02,2000,1,PIT,NL,5,11,27,0,432,169,84,13,58,73,5.25,94
32915,anderma01,2000,1,DET,AL,3,2,69,1,223,61,39,8,45,71,4.72,44
32916,andrecl01,2000,1,TOR,AL,1,2,8,0,62,34,23,6,9,12,10.02,23
32917,ankieri01,2000,1,SLN,NL,11,7,31,0,525,137,68,21,90,194,3.50,80
32918,appieke01,2000,1,OAK,AL,15,11,31,0,586,200,98,23,102,129,4.52,109
32919,armasto02,2000,1,MON,NL,7,9,17,0,285,74,46,10,50,59,4.36,49
32920,arnolja01,2000,1,LAN,NL,0,0,2,0,20,4,3,0,5,3,4.05,3
32921,arnolja01,2000,2,CHN,NL,0,3,12,1,98,34,24,1,19,13,6.61,28
32922,arrojro01,2000,1,COL,NL,5,9,19,0,304,120,68,14,46,80,6.04,77
32923,arrojro01,2000,2,BOS,AL,5,2,13,0,214,67,40,10,22,44,5.05,41
32924,arroybr01,2000,1,PIT,NL,2,6,20,0,215,88,51,10,36,50,6.40,61
32925,ashbyan01,2000,1,PHI,NL,4,7,16,0,304,113,64,17,38,51,5.68,75
32926,ashbyan01,2000,2,ATL,NL,8,6,15,0,294,103,45,12,23,55,4.13,49
32927,astacpe01,2000,1,COL,NL,12,9,32,0,589,217,115,32,77,193,5.27,119
32928,aybarma01,2000,1,COL,NL,0,1,1,0,5,5,3,1,0,0,16.20,3
32929,aybarma01,2000,2,CIN,NL,1,1,32,0,151,51,27,7,22,31,4.83,31
32930,aybarma01,2000,3,FLO,NL,1,0,21,0,82,18,8,3,13,14,2.63,8
32931,baldwja01,2000,1,CHA,AL,14,7,29,0,534,185,92,34,59,116,4.65,96
32932,balejo01,2000,1,TOR,AL,0,0,2,0,11,5,6,1,3,6,14.73,7
32933,barcelo01,2000,1,CHA,AL,4,2,22,0,117,34,16,5,9,26,3.69,17
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46669,wieckbr01,2018,1,SDN,NL,0,0,5,0,21,3,1,1,0,10,1.29,1
46670,wilkeaa01,2018,1,MIL,NL,0,1,3,0,27,12,10,4,3,10,10.00,10
46671,williau01,2018,1,WAS,NL,0,1,10,0,29,10,6,5,6,8,5.59,6
46672,willita01,2018,1,MIL,NL,1,3,56,0,159,53,25,6,25,57,4.25,28
46673,willitr01,2018,1,PIT,NL,14,10,31,0,512,146,59,15,55,126,3.11,64
46674,wilsoal01,2018,1,DET,AL,2,4,59,0,185,50,23,8,15,43,3.36,24
46675,wilsobr02,2018,1,ATL,NL,1,0,3,0,21,8,5,0,6,6,6.43,5
46676,wilsoju10,2018,1,CHN,NL,4,5,71,0,164,45,21,5,33,69,3.46,22
46677,wingetr01,2018,1,SDN,NL,0,0,22,0,57,13,8,3,11,27,3.79,8
46678,winklda01,2018,1,ATL,NL,4,0,69,2,181,52,23,3,20,69,3.43,27
46679,wislema01,2018,1,ATL,NL,1,1,7,0,80,30,16,6,5,21,5.40,16
46680,wislema01,2018,2,CIN,NL,0,0,11,0,40,11,3,2,2,11,2.03,4
46681,wittgni01,2018,1,MIA,NL,2,1,32,0,101,29,11,1,15,31,2.94,13
46682,woodal02,2018,1,LAN,NL,9,7,33,0,455,143,62,14,40,135,3.68,70
46683,woodbl01,2018,1,LAA,AL,1,0,13,0,35,8,3,1,7,10,2.31,3
46684,woodhu01,2018,1,TBA,AL,1,1,29,0,123,42,17,4,18,42,3.73,17
46685,woodrbr01,2018,1,MIL,NL,3,0,19,1,127,36,17,4,14,47,3.61,18
46686,workmbr01,2018,1,BOS,AL,6,1,43,0,124,34,15,6,16,37,3.27,15
46687,wrighky01,2018,1,ATL,NL,0,0,4,0,18,4,3,2,6,5,4.50,3
46688,wrighmi01,2018,1,BAL,AL,4,2,48,0,253,101,52,12,36,74,5.55,55
46689,wrighst01,2018,1,BOS,AL,3,1,20,1,161,41,16,5,26,42,2.68,17
46690,yacabji01,2018,1,BAL,AL,0,2,12,0,120,40,24,8,18,33,5.40,25
46691,yarbrry01,2018,1,TBA,AL,16,6,38,0,442,140,64,18,50,128,3.91,70
46692,yateski01,2018,1,SDN,NL,5,3,65,12,189,41,15,6,17,90,2.14,15
46693,zagurmi01,2018,1,MIL,NL,0,1,2,0,3,5,7,0,2,2,63.00,7
46694,zamorda01,2018,1,NYN,NL,1,0,16,0,27,6,3,1,3,16,3.00,3
46695,zastrro01,2018,1,CHN,NL,1,0,6,0,17,6,3,0,4,3,4.76,3
46696,zieglbr01,2018,1,MIA,NL,1,5,53,10,156,49,23,7,17,37,3.98,25
46697,zieglbr01,2018,2,ARI,NL,1,1,29,0,65,22,9,1,8,13,3.74,9
46698,zimmejo02,2018,1,DET,AL,7,8,25,0,394,140,66,28,26,111,4.52,76

In [5]:
batting_stats = pd.read_csv('Batting.csv')

In [6]:
batting_stats = batting_stats.drop(['IBB','HBP','SH','SF', 'GIDP', 'SB', 'CS'], axis=1)

In [7]:
batting_stats = batting_stats.loc[batting_stats['yearID'] >= 2000]

In [8]:
BA = (batting_stats['H']) / batting_stats['AB']

In [9]:
batting_stats['BA'] = BA

In [10]:
batting_stats = batting_stats.loc[batting_stats['G'] >= 81]

In [11]:
batting_stats['BA'].isnull().values.any()

True

In [12]:
batting_stats = batting_stats.dropna()

In [13]:
batting_stats['BA'].mean()

0.26535298684196873

In [14]:
pitching_stats.describe()

,yearID,stint,W,L,G,GS,CG,SHO,SV,IPouts,...,IBB,WP,HBP,BK,BFP,GF,R,SH,SF,GIDP
count,13795.000000,13795.000000,13795.000000,13795.000000,13795.000000,13795.000000,13795.000000,13795.000000,13795.000000,13795.000000,...,13795.000000,13795.000000,13795.000000,13795.000000,13795.000000,13795.000000,13795.000000,13795.000000,13795.000000,13795.000000
mean,2009.437767,1.088873,3.345632,3.345632,26.092352,6.692135,0.198260,0.081044,1.689598,179.193331,...,1.628706,2.217035,2.338673,0.209496,256.611598,6.493875,30.513519,1.999710,1.816745,5.179993
std,5.542155,0.299949,4.212907,3.675290,21.006693,10.727643,0.717678,0.352439,6.488716,178.451522,...,1.966337,2.640515,2.798197,0.534618,250.544700,10.867565,29.606591,2.626087,2.079832,5.880535
min,2000.000000,1.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2005.000000,1.000000,0.000000,0.000000,8.000000,0.000000,0.000000,0.000000,0.000000,43.000000,...,0.000000,0.000000,0.000000,0.000000,65.000000,0.000000,9.000000,0.000000,0.000000,1.000000
50%,2010.000000,1.000000,2.000000,2.000000,22.000000,0.000000,0.000000,0.000000,0.000000,122.000000,...,1.000000,1.000000,1.000000,0.000000,178.000000,2.000000,20.000000,1.000000,1.000000,3.000000
75%,2014.000000,1.000000,5.000000,5.000000,35.000000,10.000000,0.000000,0.000000,0.000000,231.000000,...,2.000000,3.000000,3.000000,0.000000,328.000000,8.000000,40.000000,3.000000,3.000000,7.000000
max,2018.000000,5.000000,24.000000,21.000000,94.000000,36.000000,11.000000,6.000000,62.000000,798.000000,...,17.000000,25.000000,21.000000,6.000000,1071.000000,79.000000,152.000000,21.000000,14.000000,40.000000

In [15]:
batting_stats.describe()

,yearID,stint,G,AB,R,H,2B,3B,HR,RBI,BB,SO,BA
count,5776.000000,5776.000000,5776.000000,5776.000000,5776.000000,5776.000000,5776.000000,5776.000000,5776.000000,5776.000000,5776.000000,5776.000000,5776.000000
mean,2008.964681,1.010388,125.038089,422.491863,59.168109,114.144737,22.918802,2.378463,14.156683,56.621364,41.521295,82.327216,0.265353
std,5.468347,0.104758,24.435485,136.222431,25.804177,43.082868,10.148106,2.461150,10.224961,27.579410,22.878710,35.147530,0.036774
min,2000.000000,1.000000,81.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2004.000000,1.000000,104.000000,319.000000,39.000000,81.000000,15.000000,1.000000,6.000000,36.000000,25.000000,57.000000,0.245652
50%,2009.000000,1.000000,128.000000,431.000000,56.500000,114.000000,22.000000,2.000000,12.000000,53.000000,37.000000,78.000000,0.266272
75%,2014.000000,1.000000,147.000000,539.000000,77.000000,148.000000,30.000000,3.000000,20.000000,74.000000,54.000000,104.000000,0.286934
max,2018.000000,3.000000,163.000000,716.000000,152.000000,262.000000,59.000000,23.000000,73.000000,160.000000,232.000000,223.000000,1.000000

In [16]:
players = pd.read_csv('People.csv')

In [22]:
type(players)

pandas.core.frame.DataFrame

In [24]:
player_name = players['debut']

In [25]:
date_time = players.to_datetime(player_name)

AttributeError: 'DataFrame' object has no attribute 'to_datetime'

In [27]:
player_name.head()[0]

'2004-04-06'

In [43]:
debut = pd.to_datetime(player_name)

In [44]:
def get_year(x):
    return x.year

In [47]:
players['Debut'] = debut

In [49]:
players = players.drop(['debut'], axis=1)

In [52]:
players['Debut Year'] = players['Debut'].apply(get_year)

In [58]:
relevant_players = players[['playerID', 'Debut Year']]

In [60]:
players

,playerID,birthYear,birthMonth,birthDay,birthCountry,birthState,birthCity,deathYear,deathMonth,deathDay,...,nameGiven,weight,height,bats,throws,finalGame,retroID,bbrefID,Debut,Debut Year
0,aardsda01,1981.0,12.0,27.0,USA,CO,Denver,NaN,NaN,NaN,...,David Allan,215.0,75.0,R,R,2015-08-23,aardd001,aardsda01,2004-04-06,2004.0
1,aaronha01,1934.0,2.0,5.0,USA,AL,Mobile,NaN,NaN,NaN,...,Henry Louis,180.0,72.0,R,R,1976-10-03,aaroh101,aaronha01,1954-04-13,1954.0
2,aaronto01,1939.0,8.0,5.0,USA,AL,Mobile,1984.0,8.0,16.0,...,Tommie Lee,190.0,75.0,R,R,1971-09-26,aarot101,aaronto01,1962-04-10,1962.0
3,aasedo01,1954.0,9.0,8.0,USA,CA,Orange,NaN,NaN,NaN,...,Donald William,190.0,75.0,R,R,1990-10-03,aased001,aasedo01,1977-07-26,1977.0
4,abadan01,1972.0,8.0,25.0,USA,FL,Palm Beach,NaN,NaN,NaN,...,Fausto Andres,184.0,73.0,L,L,2006-04-13,abada001,abadan01,2001-09-10,2001.0
5,abadfe01,1985.0,12.0,17.0,D.R.,La Romana,La Romana,NaN,NaN,NaN,...,Fernando Antonio,220.0,73.0,L,L,2017-10-01,abadf001,abadfe01,2010-07-28,2010.0
6,abadijo01,1850.0,11.0,4.0,USA,PA,Philadelphia,1905.0,5.0,17.0,...,John W.,192.0,72.0,R,R,1875-06-10,abadj101,abadijo01,1875-04-26,1875.0
7,abbated01,1877.0,4.0,15.0,USA,PA,Latrobe,1957.0,1.0,6.0,...,Edward James,170.0,71.0,R,R,1910-09-15,abbae101,abbated01,1897-09-04,1897.0
8,abbeybe01,1869.0,11.0,11.0,USA,VT,Essex,1962.0,6.0,11.0,...,Bert Wood,175.0,71.0,R,R,1896-09-23,abbeb101,abbeybe01,1892-06-14,1892.0
9,abbeych01,1866.0,10.0,14.0,USA,NE,Falls City,1926.0,4.0,27.0,...,Charles S.,169.0,68.0,L,L,1897-08-19,abbec101,abbeych01,1893-08-16,1893.0
10,abbotda01,1862.0,3.0,16.0,USA,OH,Portage,1930.0,2.0,13.0,...,Leander Franklin,190.0,71.0,R,R,1890-05-23,abbod101,abbotda01,1890-04-19,1890.0
11,abbotfr01,1874.0,10.0,22.0,USA,OH,Versailles,1935.0,6.0,11.0,...,Harry Frederick,180.0,70.0,R,R,1905-09-20,abbof101,abbotfr01,1903-04-25,1903.0
12,abbotgl01,1951.0,2.0,16.0,USA,AR,Little Rock,NaN,NaN,NaN,...,William Glenn,200.0,78.0,R,R,1984-08-08,abbog001,abbotgl01,1973-07-29,1973.0
13,abbotje01,1972.0,8.0,17.0,USA,GA,Atlanta,NaN,NaN,NaN,...,Jeffrey William,190.0,74.0,R,L,2001-09-29,abboj002,abbotje01,1997-06-10,1997.0
14,abbotji01,1967.0,9.0,19.0,USA,MI,Flint,NaN,NaN,NaN,...,James Anthony,200.0,75.0,L,L,1999-07-21,abboj001,abbotji01,1989-04-08,1989.0
15,abbotku01,1969.0,6.0,2.0,USA,OH,Zanesville,NaN,NaN,NaN,...,Kurt Thomas,180.0,71.0,R,R,2001-04-13,abbok002,abbotku01,1993-09-07,1993.0
16,abbotky01,1968.0,2.0,18.0,USA,MA,Newburyport,NaN,NaN,NaN,...,Lawrence Kyle,200.0,76.0,L,L,1996-08-24,abbok001,abbotky01,1991-09-10,1991.0
17,abbotod01,1886.0,9.0,5.0,USA,PA,New Eagle,1933.0,4.0,13.0,...,Ody Cleon,165.0,69.0,L,R,1910-10-15,abboo101,abbotod01,1910-09-10,1910.0
18,abbotpa01,1967.0,9.0,15.0,USA,CA,Van Nuys,NaN,NaN,NaN,...,Paul David,185.0,75.0,R,R,2004-08-07,abbop001,abbotpa01,1990-08-21,1990.0
19,aberal01,1927.0,7.0,31.0,USA,OH,Cleveland,1993.0,5.0,20.0,...,Albert Julius,195.0,74.0,L,L,1957-09-11,abera101,aberal01,1950-09-15,1950.0
20,abercda01,1850.0,1.0,2.0,USA,OK,Fort Towson,1939.0,11.0,11.0,...,Francis Patterson,NaN,NaN,NaN,NaN,1871-10-21,aberd101,abercda01,1871-10-21,1871.0
21,abercre01,1980.0,7.0,15.0,USA,GA,Columbus,NaN,NaN,NaN,...,Reginald Damascus,215.0,75.0,R,R,2008-09-28,aberr001,abercre01,2006-04-04,2006.0
22,abernbi01,1929.0,1.0,30.0,USA,CA,Torrance,2006.0,2.0,19.0,...,William Edward,190.0,70.0,R,R,1952-09-27,aberb101,abernbi01,1952-09-27,1952.0
23,abernbr01,1977.0,9.0,23.0,USA,GA,Atlanta,NaN,NaN,NaN,...,Michael Brent,185.0,73.0,R,R,2005-09-29,aberb001,abernbr01,2001-06-25,2001.0
24,abernte01,1921.0,10.0,30.0,USA,NC,Bynum,2001.0,11.0,16.0,...,Talmadge Lafayette,210.0,74.0,R,L,1944-04-29,abert102,abernte01,1942-09-19,1942.0
25,abernte02,1933.0,3.0,6.0,USA,NC,Stanley,2004.0,12.0,16.0,...,Theodore Wade,215.0,76.0,R,R,1972-09-30,abert101,abernte02,1955-04-13,1955.0
26,abernwo01,1915.0,2.0,1.0,USA,NC,Forest City,1994.0,12.0,5.0,...,Virgil Woodrow,170.0,72.0,L,L,1947-04-17,aberw101,abernwo01,1946-07-28,1946.0
27,aberscl01,1921.0,8.0,28.0,USA,IL,Chicago,1973.0,6.0,23.0,...,Clifford Alexander,200.0,72.0,R,R,1949-05-09,aberc101,aberscl01,1947-07-18,1947.0
28,ablesha01,1883.0,10.0,4.0,USA,TX,Terrell,1951.0,2.0,8.0,...,Harry Terrell,200.0,74.0,R,L,1911-05-05,ableh101,ablesha01,1905-09-04,1905.0
29,abnersh01,1966.0,6.0,17.0,USA,OH,Hamilton,NaN,NaN,NaN,...,Shawn Wesley,190.0,73.0,R,R,1992-10-03,abnes001,abnersh01,1987-09-08,1987.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19587,zimmejo02,1986.0,5.0,23.0,USA,WI,Auburndale,NaN,NaN,NaN,...,Jordan M.,225.0,74.0,R,R,2018-09-28,zimmj003,zimmejo02,2009-04-20,2009.0
19588,zimmero01,1913.0,9.0,13.0,USA,PA,Pine Grove,1991.0,11.0,22.0,...,Roy Franklin,187.0,74.0,L,L,1945-09-30,zimmr101,zimmero01,1945-08-27,1945.0
19589,zimmery01,1984.0,9.0,28.0,USA,NC,Washington,NaN,NaN,NaN,...,Ryan Wallace,215.0,75.0,R,R,2018-09-26,zimmr001,zimmery01,2005-09-01,2005.0
19590,zinkch01,1979.0,8.0,26.0,USA,CA,Carmichael,NaN,NaN,NaN,...,Charles Tadao,190.0,73.0,R,R,2008-08-12,zinkc001,zinkch01,2008-08-12,2008.0
19591,zinkwa01,1898.0,11.0,21.0,USA,MA,Pittsfield,1964.0,6.0,12.0,...,Walter Noble,165.0,72.0,R,R,1921-07-19,zinkw101,zinkwa01,1921-07-06,1921.0
19592,zinnfr01,1865.0,12.0,21.0,USA,PA,Phoenixville,1936.0,5.0,12.0,...,Frank Patrick,150.0,68.0,NaN,NaN,1888-05-03,zinnf101,zinnfr01,1888-04-18,1888.0
19593,zinngu01,1887.0,2.0,13.0,USA,WV,Holbrook,1949.0,10.0,6.0,...,Guy,170.0,70.0,L,R,1915-09-16,zinng101,zinngu01,1911-09-11,1911.0
19594,zinnji01,1895.0,1.0,31.0,USA,AR,Benton,1991.0,2.0,26.0,...,James Edward,195.0,72.0,L,R,1929-08-25,zinnj101,zinnji01,1919-09-04,1919.0
19595,zinsebi01,1918.0,1.0,6.0,USA,NY,Astoria,1993.0,2.0,16.0,...,William Francis,185.0,73.0,R,R,1944-08-26,zinsb101,zinsebi01,1944-08-19,1944.0
19596,zinteal01,1968.0,5.0,19.0,USA,TX,El Paso,NaN,NaN,NaN,...,Alan Michael,200.0,74.0,B,R,2004-10-03,zinta001,zinteal01,2002-06-18,2002.0
19597,zipfebu01,1938.0,11.0,18.0,USA,IL,Belleville,NaN,NaN,NaN,...,Marion Sylvester,200.0,75.0,L,R,1962-09-30,zipfb101,zipfebu01,1961-07-26,1961.0
19598,ziskri01,1949.0,2.0,6.0,USA,NY,Brooklyn,NaN,NaN,NaN,...,Richard Walter,200.0,73.0,R,R,1983-09-21,ziskr101,ziskri01,1971-09-08,1971.0
19599,zitoba01,1978.0,5.0,13.0,USA,NV,Las Vegas,NaN,NaN,NaN,...,Barry William,205.0,74.0,L,L,2015-09-30,zitob001,zitoba01,2000-07-22,2000.0
19600,zitzmbi01,1895.0,11.0,19.0,USA,NY,Long Island City,1985.0,5.0,29.0,...,William Arthur,175.0,70.0,R,R,1929-09-25,zitzb101,zitzmbi01,1919-04-27,1919.0
19601,zmiched01,1884.0,10.0,1.0,USA,OH,Cleveland,1950.0,8.0,20.0,...,Edward Albert,180.0,72.0,L,L,1911-06-01,zmice101,zmiched01,1910-07-23,1910.0
19602,zobribe01,1981.0,5.0,26.0,USA,IL,Eureka,NaN,NaN,NaN,...,Benjamin Thomas,210.0,75.0,B,R,2018-10-01,zobrb001,zobribe01,2006-08-01,2006.0
19603,zoccope01,1977.0,2.0,6.0,USA,NY,Bronx,NaN,NaN,NaN,...,Peter Jude,200.0,74.0,L,R,2003-09-28,zoccp001,zoccope01,2003-09-05,2003.0
19604,zoldasa01,1918.0,12.0,8.0,USA,NY,Brooklyn,1966.0,8.0,25.0,...,Samuel Walter,185.0,71.0,L,L,1952-08-26,zolds101,zoldasa01,1944-05-13,1944.0
19605,zoskyed01,1968.0,2.0,10.0,USA,CA,Whittier,NaN,NaN,NaN,...,Edward James,175.0,72.0,R,R,2000-10-01,zoske001,zoskyed01,1991-09-02,1991.0
19606,zuberbi01,1913.0,3.0,26.0,USA,IA,Middle Amana,1982.0,11.0,2.0,...,William Henry,195.0,74.0,R,R,1947-09-23,zubeb101,zuberbi01,1936-09-16,1936.0
19607,zuberjo01,1969.0,12.0,10.0,USA,CA,Encino,NaN,NaN,NaN,...,Jon Edward,190.0,73.0,L,L,1998-09-27,zubej001,zuberjo01,1996-04-19,1996.0
19608,zuletju01,1975.0,3.0,28.0,Panama,Panama,Panama,NaN,NaN,NaN,...,Julio Ernesto,230.0,78.0,R,R,2001-06-25,zulej001,zuletju01,2000-04-06,2000.0
19609,zumayjo01,1984.0,11.0,9.0,USA,CA,Chula Vista,NaN,NaN,NaN,...,Joel Martin,215.0,75.0,R,R,2010-06-28,zumaj001,zumayjo01,2006-04-03,2006.0
19610,zuninmi01,1991.0,3.0,25.0,USA,FL,Cape Coral,NaN,NaN,NaN,...,Michael Accorsi,220.0,74.0,R,R,2018-09-29,zunim001,zuninmi01,2013-06-12,2013.0
19611,zupcibo01,1966.0,8.0,18.0,USA,PA,Pittsburgh,NaN,NaN,NaN,...,Robert,220.0,76.0,R,R,1994-08-04,zupcb001,zupcibo01,1991-09-07,1991.0
19612,zupofr01,1939.0,8.0,29.0,USA,CA,San Francisco,2005.0,3.0,25.0,...,Frank Joseph,182.0,71.0,L,R,1961-05-09,zupof101,zupofr01,1957-07-01,1957.0
19613,zuvelpa01,1958.0,10.0,31.0,USA,CA,San Mateo,NaN,NaN,NaN,...,Paul,173.0,72.0,R,R,1991-05-02,zuvep001,zuvelpa01,1982-09-04,1982.0
19614,zuverge01,1924.0,8.0,20.0,USA,MI,Holland,2014.0,9.0,8.0,...,George,195.0,76.0,R,R,1959-06-15,zuveg101,zuverge01,1951-04-21,1951.0
19615,zwilldu01,1888.0,11.0,2.0,USA,MO,St. Louis,1978.0,3.0,27.0,...,Edward Harrison,160.0,66.0,L,L,1916-07-12,zwild101,zwilldu01,1910-08-14,1910.0
19616,zychto01,1990.0,8.0,7.0,USA,IL,Monee,NaN,NaN,NaN,...,Anthony Aaron,190.0,75.0,R,R,2017-08-19,zycht001,zychto01,2015-09-04,2015.0

In [62]:
test = players[['playerID','nameGiven']]

In [63]:
pd.merge(batting_stats,test)

,playerID,yearID,stint,teamID,lgID,G,AB,R,H,2B,3B,HR,RBI,BB,SO,BA,nameGiven
0,abreubo01,2000,1,PHI,NL,154,576,103,182,42,10,25,79.0,100,116.0,0.315972,Bob Kelly
1,abreubo01,2001,1,PHI,NL,162,588,118,170,48,4,31,110.0,106,137.0,0.289116,Bob Kelly
2,abreubo01,2002,1,PHI,NL,157,572,102,176,50,6,20,85.0,104,117.0,0.307692,Bob Kelly
3,abreubo01,2003,1,PHI,NL,158,577,99,173,35,1,20,101.0,109,126.0,0.299827,Bob Kelly
4,abreubo01,2004,1,PHI,NL,159,574,118,173,47,1,30,105.0,127,116.0,0.301394,Bob Kelly
5,abreubo01,2005,1,PHI,NL,162,588,104,168,37,1,24,102.0,117,134.0,0.285714,Bob Kelly
6,abreubo01,2006,1,PHI,NL,98,339,61,94,25,2,8,65.0,91,86.0,0.277286,Bob Kelly
7,abreubo01,2007,1,NYA,AL,158,605,123,171,40,5,16,101.0,84,115.0,0.282645,Bob Kelly
8,abreubo01,2008,1,NYA,AL,156,609,100,180,39,4,20,100.0,73,109.0,0.295567,Bob Kelly
9,abreubo01,2009,1,LAA,AL,152,563,96,165,29,3,15,103.0,94,113.0,0.293073,Bob Kelly
10,abreubo01,2010,1,LAA,AL,154,573,88,146,41,1,20,78.0,87,132.0,0.254799,Bob Kelly
11,abreubo01,2011,1,LAA,AL,142,502,54,127,30,1,8,60.0,78,113.0,0.252988,Bob Kelly
12,abreubo01,2012,2,LAN,NL,92,195,28,48,8,1,3,19.0,35,51.0,0.246154,Bob Kelly
13,agbaybe01,2000,1,NYN,NL,119,350,59,101,19,1,15,60.0,54,68.0,0.288571,Benny Peter
14,agbaybe01,2001,1,NYN,NL,91,296,28,82,14,2,6,27.0,36,73.0,0.277027,Benny Peter
15,alexama02,2000,1,BOS,AL,101,194,30,41,4,3,4,19.0,13,41.0,0.211340,Manuel de Jesus
16,alfoned01,2000,1,NYN,NL,150,544,109,176,40,2,25,94.0,95,70.0,0.323529,Edgardo Antonio
17,alfoned01,2001,1,NYN,NL,124,457,64,111,22,0,17,49.0,51,62.0,0.242888,Edgardo Antonio
18,alfoned01,2002,1,NYN,NL,135,490,78,151,26,0,16,56.0,62,55.0,0.308163,Edgardo Antonio
19,alfoned01,2003,1,SFN,NL,142,514,56,133,25,2,13,81.0,58,41.0,0.258755,Edgardo Antonio
20,alfoned01,2004,1,SFN,NL,139,519,66,150,26,1,11,77.0,46,40.0,0.289017,Edgardo Antonio
21,alfoned01,2005,1,SFN,NL,109,368,36,102,17,1,2,43.0,27,34.0,0.277174,Edgardo Antonio
22,alicelu01,2000,1,TEX,AL,139,540,85,159,25,8,6,63.0,59,75.0,0.294444,Luis Rene
23,alicelu01,2001,1,KCA,AL,113,387,44,106,16,4,4,32.0,23,56.0,0.273902,Luis Rene
24,alicelu01,2002,1,KCA,AL,94,237,28,54,8,2,1,23.0,32,34.0,0.227848,Luis Rene
25,alomaro01,2000,1,CLE,AL,155,610,111,189,40,2,19,89.0,64,82.0,0.309836,Roberto
26,alomaro01,2001,1,CLE,AL,157,575,113,193,34,12,20,100.0,80,71.0,0.335652,Roberto
27,alomaro01,2002,1,NYN,NL,149,590,73,157,24,4,11,53.0,57,83.0,0.266102,Roberto
28,alomasa02,2000,1,CLE,AL,97,356,44,103,16,2,7,42.0,16,41.0,0.289326,Santos
29,aloumo01,2000,1,HOU,NL,126,454,82,161,28,2,30,114.0,52,45.0,0.354626,Moises Rojas
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5746,hernate01,2018,1,TOR,AL,134,476,67,114,29,7,22,57.0,41,163.0,0.239496,Teoscar Jose
5747,hicksjo02,2018,1,DET,AL,81,288,35,75,12,1,9,32.0,22,84.0,0.260417,John Austin
5748,hoskirh01,2018,1,PHI,NL,153,558,89,137,38,0,34,96.0,87,150.0,0.245520,Rhys Dean
5749,jonesja07,2018,1,DET,AL,129,429,54,89,22,6,11,34.0,24,142.0,0.207459,JaCoby Mylon
5750,kempto01,2018,1,HOU,AL,97,255,37,67,15,0,6,30.0,32,44.0,0.262745,Anthony Allen
5751,kineris01,2018,1,TEX,AL,111,356,43,93,18,2,4,34.0,28,62.0,0.261236,Isiah
5752,kingesc01,2018,1,PHI,NL,147,452,55,102,23,2,8,35.0,24,126.0,0.225664,Scott M.
5753,knappan01,2018,1,PHI,NL,84,187,19,37,6,2,4,15.0,24,75.0,0.197861,Andrew Michael
5754,mcmahry01,2018,1,COL,NL,91,181,17,42,9,1,5,19.0,18,64.0,0.232044,Ryan Patrick
5755,moncayo01,2018,1,CHA,AL,149,578,73,136,32,6,17,61.0,67,217.0,0.235294,Yoan Manuel
5756,moranco01,2018,1,PIT,NL,144,415,49,115,19,1,11,58.0,39,82.0,0.277108,Colin Richard
5757,muncyma01,2018,1,LAN,NL,137,395,75,104,17,2,35,79.0,79,131.0,0.263291,Maxwell Steven
5758,munozya01,2018,1,SLN,NL,108,293,39,81,16,0,8,42.0,30,71.0,0.276451,Yairo
5759,murphjr01,2018,1,ARI,NL,87,208,19,42,9,0,9,24.0,11,71.0,0.201923,John Ryan
5760,nimmobr01,2018,1,NYN,NL,140,433,77,114,28,8,17,47.0,80,140.0,0.263279,Brandon Tate
5761,ohtansh01,2018,1,LAA,AL,114,326,59,93,21,2,22,61.0,37,102.0,0.285276,Shohei
5762,olsonma02,2018,1,OAK,AL,162,580,85,143,33,0,29,84.0,70,163.0,0.246552,Matthew Kent
5763,palkada01,2018,1,CHA,AL,124,417,56,100,15,3,27,67.0,30,153.0,0.239808,Daniel Bennett
5764,reyesfr01,2018,1,SDN,NL,87,261,36,73,9,0,16,31.0,24,80.0,0.279693,Franmil Federico
5765,reyesvi01,2018,1,DET,AL,100,212,35,47,5,3,1,12.0,5,46.0,0.221698,Victor Jose
5766,riddljt01,2018,1,MIA,NL,102,308,28,71,10,4,9,36.0,20,67.0,0.230519,Joshua Travis
5767,riverya01,2018,1,MIA,NL,111,139,13,24,3,0,1,9.0,19,51.0,0.172662,Yadiel
5768,roberda10,2018,1,TBA,AL,88,282,46,74,16,0,9,34.0,43,77.0,0.262411,Daniel Ray
5769,rosaram01,2018,1,NYN,NL,154,554,76,142,26,8,9,51.0,29,119.0,0.256318,German Amed
5770,sotoju01,2018,1,WAS,NL,116,414,77,121,25,1,22,70.0,79,99.0,0.292271,Juan Jose
5771,stassma01,2018,1,HOU,AL,88,221,28,50,13,0,8,27.0,23,74.0,0.226244,Max Robert
5772,torregl01,2018,1,NYA,AL,123,431,54,117,16,1,24,77.0,42,122.0,0.271462,Gleyber David
5773,villach01,2018,1,SDN,NL,110,351,42,83,15,0,20,46.0,23,104.0,0.236467,Christian
5774,wendljo01,2018,1,TBA,AL,139,487,62,146,33,6,7,61.0,37,96.0,0.299795,Joseph Patrick
5775,winkeje01,2018,1,CIN,NL,89,281,38,84,16,0,7,43.0,49,46.0,0.298932,Jesse